[toolchain]

[features]
resolution = true
skip-lint = false


[programs.devnet]
vote_program_solana = "H6tgcEthAFnd2aiJp8ne4mE7FaonG1eP9ryXeodqn1ep"
[programs.localnet]
vote_program_solana = "H6tgcEthAFnd2aiJp8ne4mE7FaonG1eP9ryXeodqn1ep"
[programs.mainnet]
vote_program_solana = "H6tgcEthAFnd2aiJp8ne4mE7FaonG1eP9ryXeodqn1ep"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
