[toolchain]

[features]
resolution = true
skip-lint = false


[programs.devnet]
vote_program_solana = "HVFEvAbJRwRXJD3cBFVHaBhJn41nxuChyb2VhxFbwAeB"
[programs.localnet]
vote_program_solana = "HVFEvAbJRwRXJD3cBFVHaBhJn41nxuChyb2VhxFbwAeB"
[programs.mainnet]
vote_program_solana = "HVFEvAbJRwRXJD3cBFVHaBhJn41nxuChyb2VhxFbwAeB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
